import { act, renderHook, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { useHhAccounts } from "./use-hh-accounts";
const service = vi.hoisted(() => ({ list: vi.fn(), start: vi.fn(), select: vi.fn(), remove: vi.fn() }));
vi.mock("./service", () => ({ hhAccountService: service }));
const empty = { accounts: [], active_account_id: null };
describe("useHhAccounts popup", () => {
  beforeEach(() => { vi.clearAllMocks(); service.list.mockResolvedValue(empty); service.start.mockResolvedValue("https://hh.test/oauth"); });
  it("сообщает о заблокированном popup", async () => { vi.spyOn(window, "open").mockReturnValue(null); const { result } = renderHook(() => useHhAccounts()); await waitFor(() => expect(result.current.loading).toBe(false)); await act(() => result.current.connect()); expect(result.current.error).toMatch(/заблокировал/); expect(result.current.pending).toBe(false); });
  it("принимает success только от своего popup и origin и обновляет список", async () => { const popup = { closed: false, close: vi.fn() } as unknown as Window; vi.spyOn(window, "open").mockReturnValue(popup); const { result } = renderHook(() => useHhAccounts()); await waitFor(() => expect(result.current.loading).toBe(false)); await act(() => result.current.connect()); act(() => window.dispatchEvent(new MessageEvent("message", { origin: "https://evil.test", source: popup, data: { type: "haintly:hh-oauth-success" } }))); expect(service.list).toHaveBeenCalledTimes(1); act(() => window.dispatchEvent(new MessageEvent("message", { origin: window.location.origin, source: popup, data: { type: "haintly:hh-oauth-success" } }))); await waitFor(() => expect(service.list).toHaveBeenCalledTimes(2)); expect(popup.close).toHaveBeenCalled(); });
  it("снимает pending после ручного закрытия", async () => { vi.useFakeTimers(); const popup = { closed: false, close: vi.fn() } as unknown as Window; vi.spyOn(window, "open").mockReturnValue(popup); const { result } = renderHook(() => useHhAccounts()); await act(async () => { await Promise.resolve(); }); await act(() => result.current.connect()); (popup as unknown as { closed: boolean }).closed = true; await act(async () => { vi.advanceTimersByTime(350); }); expect(result.current.pending).toBe(false); vi.useRealTimers(); });
  it("удаляет без native confirm и возвращает успех для modal", async () => { service.remove.mockResolvedValue(undefined); const confirm = vi.spyOn(window, "confirm"); const { result } = renderHook(() => useHhAccounts()); await waitFor(() => expect(result.current.loading).toBe(false)); let removed = false; await act(async () => { removed = await result.current.remove("fixture-1"); }); expect(removed).toBe(true); expect(service.remove).toHaveBeenCalledWith("fixture-1"); expect(confirm).not.toHaveBeenCalled(); expect(service.list).toHaveBeenCalledTimes(2); });
  it("возвращает ошибку удаления для сохранения modal", async () => { service.remove.mockRejectedValue(new Error("Недоступно")); const { result } = renderHook(() => useHhAccounts()); await waitFor(() => expect(result.current.loading).toBe(false)); let removed = true; await act(async () => { removed = await result.current.remove("fixture-1"); }); expect(removed).toBe(false); expect(result.current.error).toBe("Недоступно"); expect(result.current.pending).toBe(false); });
});
