name: CheckAndDeploy

on:
  push:
    branches:
      - release

env:
  IMAGE: ghcr.io/igor-526/haintly_main-fe

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install deps
        run: npm install

      - name: test
        run: make test

      - name: lint
        run: make lint

      - name: build
        run: make build

  build_deploy:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
            PORT=3101
      
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
    
      - uses: azure/setup-helm@v4

      - name: Deploy
        run: |
          helm upgrade --install haintly-main-fe .helm/ \
            --namespace haintly \
            --create-namespace \
            --set imageTag=${{ github.sha }} \
            --wait